# backend/main.py
from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv

from app.services.pdf_service import extract_text_from_pdf
from app.services.ai_service import parse_text_to_schema

load_dotenv()

app = FastAPI(title="PlanSync AI Engine", version="1.0.0")

# Enable CORS so your future React interface can call this API locally on your Mac
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health")
def health_check():
    return {"status": "healthy", "service": "plansync-ai-core"}

@app.post("/api/v1/analyze-plan")
async def analyze_plan_document(file: UploadFile = File(...)):
    """
    Accepts PDF upload, extracts data, and serves the structured configuration JSON.
    """
    if not file.filename.endswith('.pdf'):
        raise HTTPException(status_code=400, detail="Invalid file type. Only PDF uploads are supported.")
        
    try:
        # Read file directly into an in-memory byte stream
        pdf_bytes = await file.read()
        
        # 1. Run Text Extraction
        filtered_text = extract_text_from_pdf(pdf_bytes)
        
        if not filtered_text.strip():
            raise HTTPException(status_code=422, detail="No relevant configuration sections identified in document.")
            
        # 2. Feed text blocks to AI schema mapper
        structured_config = parse_text_to_schema(filtered_text)
        
        return structured_config
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Internal Processing Error: {str(e)}")


# Add this import at the top of main.py if not already there
from fastapi import UploadFile, File, Form
from app.services.census_engine import cleanse_employee_census
import json

@app.post("/api/v1/cleanse-census")
async def upload_census_endpoint(
    file: UploadFile = File(...),
    extracted_rules_json: str = Form(...)  # Accepts the JSON string generated by the AI
):
    # Read the uploaded CSV data
    contents = await file.read()
    csv_text_stream = contents.decode("utf-8")
    
    # Convert the stringified frontend rules back into a native Python dictionary
    plan_rules = json.loads(extracted_rules_json)
    
    # Execute our automated auditing logic
    results = cleanse_employee_census(csv_text_stream, plan_rules)
    
    return results